In [16]:
# モジュールのインポート

import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib
import datetime
import jpholiday
import sqlite3
import seaborn as sns

In [17]:
results = pd.read_csv('../weather_yokohama.csv', index_col = 0)

In [18]:
results.columns

Index(['平均気温(℃)', '平均気温(℃)1', '平均気温(℃)2', '最高気温(℃)', '最高気温(℃)1', '最高気温(℃)2',
       '最低気温(℃)', '最低気温(℃)1', '最低気温(℃)2', '降水量の合計(mm)', '降水量の合計(mm)1',
       '降水量の合計(mm)2', '降水量の合計(mm).1', '平均風速(m/s)', '平均風速(m/s)1', '平均風速(m/s)2',
       '最大風速(m/s)', '最大風速(m/s)1', '最大風速(m/s)2', '最大風速(m/s)3', '最大風速(m/s)4',
       '平均蒸気圧(hPa)', '平均蒸気圧(hPa)1', '平均蒸気圧(hPa)2'],
      dtype='object')

In [19]:
df = results[['平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '平均風速(m/s)', '最大風速(m/s)', '平均蒸気圧(hPa)']]

In [20]:
df['日付'] = pd.to_datetime(df.index)

<ipython-input-20-3a584d3c28b8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['日付'] = pd.to_datetime(df.index)

In [21]:
df.columns = ['TempAve', 'TempMax', 'TempMin', 'RainMm', 'WinMsAve', 'WinMsMax', 'hPA', 'Date']
df

,TempAve,TempMax,TempMin,RainMm,WinMsAve,WinMsMax,hPA,Date
年月日,,,,,,,,
01/04/2018,16.1,21.0,11.8,0.0,4.6,7.9,11.8,2018-01-04
02/04/2018,17.6,23.5,13.9,0.0,2.7,4.9,13.5,2018-02-04
03/04/2018,18.2,23.5,15.0,0.0,2.9,5.5,15.1,2018-03-04
04/04/2018,20.2,25.8,15.6,0.0,4.1,10.2,15.0,2018-04-04
05/04/2018,13.5,15.9,11.8,0.0,3.0,5.5,11.4,2018-05-04
...,...,...,...,...,...,...,...,...
06/04/2021,11.2,15.9,7.6,0.0,4.2,7.0,8.2,2021-06-04
07/04/2021,13.3,18.2,9.0,0.0,2.8,4.4,9.0,2021-07-04
08/04/2021,14.2,18.8,11.0,0.0,4.0,6.7,9.0,2021-08-04
09/04/2021,12.2,16.8,9.4,0.0,3.6,10.7,6.7,2021-09-04
10/04/2021,10.5,14.6,7.4,0.0,3.8,7.8,5.3,2021-10-04

In [9]:
import dataset as ds

db = ds.connect('sqlite:///../fishing_result.db')
df.to_sql("weathers", db.engine, if_exists="replace")